/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vvs.mockito.examplo.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        System.out.println("Running test");
        assertEquals("Hello World!", MessageUtils.getMessage());
    }

    @Test public void testAdd() {
        assertEquals(42, Integer.sum(19, 23));
    }
}
