/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vvs.mockito.examplo.app;

import vvs.mockito.examplo.list.LinkedList;

import static vvs.mockito.examplo.utilities.StringUtils.join;
import static vvs.mockito.examplo.utilities.StringUtils.split;
import static vvs.mockito.examplo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
