/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vvs.mockito.examplo.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello World!";
    }
}
